export { ingest, type IngestOptions, type IngestResult, type LLMProvider } from "./ingestion/index.js";
export { discover, type DiscoverOptions } from "./discovery/index.js";
export { compose, type ComposeOptions, type ComposeResult, type ConflictResult } from "./composition/index.js";
export {
  requestDeviceCode,
  pollForToken,
  listRepos,
  indexRepo,
  loadConfig,
  saveConfig,
  getToken,
  saveToken,
  getSessionToken,
  saveSessionToken,
  clearSessionToken,
  lastTokenStorage,
  lastConfigWasWorldReadable,
  loadRepoProfiles,
  saveRepoProfile,
  loadIdeas,
  saveIdeas,
  getIdeasByIds,
  getRecentIdeas,
  loadSessions,
  saveSession,
  getLatestSession,
  type IndexRepoOptions,
  type GitHubRepo,
  type DeviceCodeResponse,
  type GitHubToken,
  type FondofConfig,
  type IngestSession,
} from "./project/index.js";
export {
  forgeSkill,
  recordUse,
  challengeSkill,
  getSignal,
  getTopSkills,
  getSkillOnChain,
  loadPoolConfig,
  SKILL_POOL_ABI,
  type PoolConfig,
  type SkillOnChain,
  type ForgeReceipt,
  type UseReceipt,
  type ChallengeReceipt,
} from "./relayer/index.js";
export {
  createEmbeddingProvider,
  cosineSimilarity,
  findTopMatches,
  type EmbeddingProvider,
  type SimilarityResult,
} from "./embeddings/index.js";
export {
  searchSkills,
  searchSourceMaterial,
  firecrawlExtract,
  tinyFishSearch,
  tinyFishFetch,
  type ExaSearchResult,
  type FirecrawlResult,
  type TinyFishSearchResult,
} from "./search/index.js";
